import { useMemo, useState, type ReactNode } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import {
  ArrowLeft, BarChart3, Bot, CalendarCheck, CheckCircle2, Clock3, Headphones,
  Lock, MessageCircle, Phone, PhoneMissed, Search, Sparkles, TrendingUp,
  UserRoundCheck, UsersRound, WalletCards,
} from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useClinicOS } from '../../../context/ClinicOSContext'
import { CLINIC_PLANS, getOverallUsage, getUsageMetrics, usagePercentage } from '../../../lib/clinicOSProduct'
import {
  saveClinicKnowledgeItem, updateClinicOpportunity, useClinicAICalls,
  useClinicAppointments, useClinicDoctors, useClinicKnowledge, useClinicMessages,
  useClinicOpportunities, useClinicServices,
} from '../../../lib/clinicOSQueries'
import { useToast } from '../../../components/clinicOS/ui/Toast'
import './clinic-ai-dashboard.css'

const SUPPORT_WHATSAPP = 'https://wa.me/966546666005'
const nf = new Intl.NumberFormat('ar-SA')
const dateFmt = new Intl.DateTimeFormat('ar-SA', { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' })
const dayFmt = new Intl.DateTimeFormat('ar-SA', { weekday: 'short' })

const PageHeader = ({ title, subtitle, action }: { title: string; subtitle: string; action?: ReactNode }) => (
  <div className="clinic-ai-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>
)

const Metric = ({ icon: Icon, label, value, description, tone = 'violet' }: { icon: typeof TrendingUp; label: string; value: ReactNode; description: string; tone?: 'violet'|'mint'|'amber'|'blue'|'rose' }) => {
  const tones = { violet: ['#f0efff','#6557d9'], mint: ['#eafaf5','#0f9f78'], amber: ['#fff7e8','#c77a18'], blue: ['#edf7ff','#2780c3'], rose: ['#fff0f2','#d44b5c'] }
  return <div className="clinic-card clinic-kpi"><div className="clinic-kpi-icon" style={{ background: tones[tone][0], color: tones[tone][1] }}><Icon size={18}/></div><div className="clinic-kpi-label">{label}</div><div className="clinic-kpi-value">{value}</div><div className="clinic-kpi-description">{description}</div></div>
}

const EmptyState = ({ icon: Icon = Sparkles, title, body, action }: { icon?: typeof Sparkles; title: string; body: string; action?: ReactNode }) => (
  <div className="clinic-empty-state"><Icon size={24}/><strong>{title}</strong><span>{body}</span>{action}</div>
)

const LoadingState = () => <div className="clinic-card"><EmptyState icon={Clock3} title="جاري تحميل بيانات العيادة" body="لحظات ونجهز لك أحدث البيانات."/></div>

const UpgradeLocked = ({ missed = false }: { missed?: boolean }) => (
  <div className="clinic-card clinic-lock"><div className="clinic-lock-inner"><div className="clinic-lock-icon"><Lock size={28}/></div><h1>{missed ? 'استعادة المكالمات الفائتة ضمن باقة AI Pro' : 'المكالمات الذكية ضمن باقة AI Pro'}</h1><p>فعّل موظف الاستقبال الصوتي للرد خارج الدوام وتحويل المكالمات إلى حجوزات قابلة للمتابعة.</p><div className="clinic-benefits">{['الرد خارج الدوام','فهم طلب العميل','تحويل المكالمة إلى حجز','ملخص واضح للموظف','متابعة الفرص غير المكتملة'].map(item => <div className="clinic-benefit" key={item}><CheckCircle2 size={14} color="#0f9f78"/> {item}</div>)}</div><Link className="clinic-action" to="/clinic-os/dashboard/plans">عرض الباقات <ArrowLeft size={15}/></Link></div></div>
)

const whatsappLink = (phone: string, message: string) => {
  const digits = phone.replace(/\D/g, '').replace(/^0/, '966')
  return `https://wa.me/${digits}?text=${encodeURIComponent(message)}`
}

export const SystemValuePage = () => {
  const { companyId, isDemo, accountLoading, usageSummary } = useClinicOS()
  const { data: appointments = [], loading } = useClinicAppointments(companyId, undefined, isDemo)
  const { data: messages = [] } = useClinicMessages(companyId, isDemo)
  const { data: calls = [] } = useClinicAICalls(companyId, isDemo)
  const { data: opportunities = [] } = useClinicOpportunities(companyId, isDemo)
  const { data: services = [] } = useClinicServices(companyId, isDemo)
  if (accountLoading || loading) return <LoadingState/>

  const month = new Date().toISOString().slice(0, 7)
  const monthAppointments = appointments.filter(a => a.appointment_date?.startsWith(month))
  const bookings = monthAppointments.filter(a => !['cancelled','no_show'].includes(a.status)).length
  const completed = monthAppointments.filter(a => a.status === 'completed').length
  const conversations = usageSummary.conversations || new Set(messages.map(m => m.recipient_phone)).size
  const estimatedRevenue = monthAppointments.reduce((sum, a) => sum + Number(services.find(s => s.id === a.service_id)?.price || 0), 0)
  const daily = Array.from({ length: 7 }, (_, index) => {
    const d = new Date(); d.setDate(d.getDate() - 6 + index)
    const key = d.toISOString().slice(0, 10)
    return { day: dayFmt.format(d), value: appointments.filter(a => a.appointment_date === key).length }
  })
  const serviceMap = monthAppointments.reduce<Record<string, number>>((acc, a) => { acc[a.service_name || 'غير محدد'] = (acc[a.service_name || 'غير محدد'] || 0) + 1; return acc }, {})
  const serviceData = Object.entries(serviceMap).map(([name, value]) => ({ name, value })).slice(0, 5)
  return <div className="clinic-ai-page"><PageHeader title="قيمة النظام هذا الشهر" subtitle="أرقام فعلية من الحجوزات والمحادثات والمكالمات المسجلة في حساب العيادة."/>
    <div className="clinic-kpi-grid"><Metric icon={CalendarCheck} label="الحجوزات" value={nf.format(bookings)} description="حجز غير ملغي" tone="mint"/><Metric icon={CheckCircle2} label="المواعيد المكتملة" value={nf.format(completed)} description="زيارة مكتملة" tone="blue"/><Metric icon={MessageCircle} label="المحادثات" value={nf.format(conversations)} description="عميل تم التعامل معه"/><Metric icon={Phone} label="المكالمات" value={nf.format(calls.length)} description="مكالمة مسجلة" tone="amber"/><Metric icon={TrendingUp} label="فرص المتابعة" value={nf.format(opportunities.filter(o=>o.status!=='closed').length)} description="فرصة ما زالت مفتوحة" tone="rose"/><Metric icon={WalletCards} label="قيمة الحجوزات" value={`${nf.format(estimatedRevenue)} ر.س`} description="حسب أسعار الخدمات" tone="mint"/></div>
    {!appointments.length && !messages.length && !calls.length ? <div className="clinic-card"><EmptyState title="لا توجد نتائج بعد" body="تبدأ هذه الصفحة من الصفر وتتحرك تلقائياً مع أول محادثة أو حجز أو مكالمة حقيقية."/></div> : <div className="clinic-two-col"><div className="clinic-card clinic-section"><div className="clinic-section-head"><h2>الحجوزات خلال 7 أيام</h2></div><ResponsiveContainer width="100%" height={240}><BarChart data={daily}><CartesianGrid stroke="#eef1f6" vertical={false}/><XAxis dataKey="day" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" name="الحجوزات" fill="#6557d9" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="clinic-card clinic-section"><div className="clinic-section-head"><h2>الخدمات الأكثر حجزاً</h2></div>{serviceData.length ? <ResponsiveContainer width="100%" height={240}><PieChart><Pie data={serviceData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={80} paddingAngle={3}>{serviceData.map((_,i)=><Cell key={i} fill={['#6557d9','#0f9f78','#2780c3','#c77a18','#d9deea'][i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer> : <EmptyState title="لا توجد خدمات محجوزة" body="أضف الخدمات ثم سجّل أول موعد لعرض التوزيع."/>}</div></div>}
  </div>
}

export const ConversationsPage = () => {
  const { companyId, isDemo } = useClinicOS(); const [filter,setFilter] = useState('الكل'); const [query,setQuery] = useState(''); const [selected,setSelected] = useState('')
  const { data: messages = [], loading } = useClinicMessages(companyId, isDemo)
  const groups = useMemo(() => Object.values(messages.reduce<Record<string,{phone:string;name:string;messages:typeof messages}>>((acc,m)=>{ const key=m.recipient_phone||'unknown'; if(!acc[key]) acc[key]={phone:key,name:m.recipient_name||'عميل',messages:[]}; acc[key].messages.push(m); return acc },{})).filter(g => (filter==='الكل'||g.messages.some(m=>m.status===filter)) && `${g.name} ${g.phone}`.includes(query)), [messages,filter,query])
  const active = groups.find(g=>g.phone===selected)
  return <div className="clinic-ai-page"><PageHeader title="المحادثات" subtitle="سجل الرسائل الحقيقي المرتبط بكل عميل، مع حالة التسليم وآخر تواصل." action={<div className="clinic-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالاسم أو الجوال"/></div>}/><div className="clinic-filter-row">{['الكل','pending','sent','delivered','read','failed'].map(f=><button key={f} onClick={()=>setFilter(f)} className={`clinic-filter ${filter===f?'active':''}`}>{({pending:'قيد الإرسال',sent:'مرسلة',delivered:'مستلمة',read:'مقروءة',failed:'فشلت'} as Record<string,string>)[f]||f}</button>)}</div>{loading?<LoadingState/>:<div className="clinic-card clinic-section">{groups.length?<div className="clinic-list">{groups.map(row=>{const last=row.messages[0];return <button className="clinic-list-row clinic-row-button" key={row.phone} onClick={()=>setSelected(row.phone)}><div><strong>{row.name}</strong><div className="clinic-muted">{row.phone}</div></div><div><strong>{last.body}</strong><div className="clinic-muted">{last.message_type}</div></div><span className={`clinic-badge ${last.status==='failed'?'danger':last.status==='read'?'success':''}`}>{last.status}</span><div className="clinic-muted">{dateFmt.format(new Date(last.created_at))}</div><span className="clinic-action secondary">عرض السجل</span></button>})}</div>:<EmptyState icon={MessageCircle} title="لا توجد محادثات بعد" body="ستظهر المحادثات هنا فور إرسال أول رسالة من النظام."/>}</div>}{active&&<div className="clinic-dialog-backdrop" onClick={()=>setSelected('')}><div className="clinic-dialog" onClick={e=>e.stopPropagation()}><div className="clinic-section-head"><div><h2>{active.name}</h2><p>{active.phone}</p></div><button className="clinic-action ghost" onClick={()=>setSelected('')}>إغلاق</button></div><div className="clinic-conversation-thread">{[...active.messages].reverse().map(m=><div className="clinic-message-bubble" key={m.id}><p>{m.body}</p><span>{dateFmt.format(new Date(m.created_at))} · {m.status}</span></div>)}</div></div></div>}</div>
}

export const LeadsPage = () => {
  const { companyId, isDemo } = useClinicOS(); const { data: rows = [], loading } = useClinicOpportunities(companyId,isDemo)
  const open = rows.filter(r=>r.status!=='closed')
  return <div className="clinic-ai-page"><PageHeader title="العملاء المحتملون" subtitle="عملاء حقيقيون أبدوا اهتماماً ولم يُغلق طلبهم بعد."/><div className="clinic-kpi-grid"><Metric icon={TrendingUp} label="أولوية عالية" value={open.filter(r=>r.priority==='high').length} description="ابدأ بهم الآن" tone="rose"/><Metric icon={UsersRound} label="يحتاجون متابعة" value={open.length} description="فرص مفتوحة" tone="amber"/><Metric icon={MessageCircle} label="قادمين من واتساب" value={open.filter(r=>r.opportunity_type?.includes('whatsapp')).length} description="حسب مصدر الفرصة" tone="mint"/><Metric icon={UserRoundCheck} label="تم إغلاقها" value={rows.filter(r=>r.status==='closed').length} description="فرص تمت معالجتها" tone="blue"/></div><div className="clinic-card clinic-section">{loading?<EmptyState icon={Clock3} title="جاري التحميل" body="نحدّث قائمة العملاء المحتملين."/>:open.length?<div className="clinic-list">{open.map(row=><div className="clinic-list-row" key={row.id}><div><strong>{row.customer_name||'عميل'}</strong><div className="clinic-muted">{row.customer_phone}</div></div><div>{row.interested_service||'خدمة غير محددة'}</div><span className={`clinic-badge ${row.priority==='high'?'danger':'warning'}`}>{row.priority==='high'?'عالية':'متوسطة'}</span><div className="clinic-muted">{row.last_contact_at?dateFmt.format(new Date(row.last_contact_at)):'لم تتم المتابعة'}</div><a className="clinic-action secondary" href={whatsappLink(row.customer_phone,`مرحباً ${row.customer_name||''}، يسعدنا مساعدتك في إكمال حجز ${row.interested_service||'موعدك'}.`)} target="_blank" rel="noreferrer">متابعة عبر واتساب</a></div>)}</div>:<EmptyState icon={UsersRound} title="لا توجد فرص مفتوحة" body="أي عميل لا يكمل الحجز سيظهر هنا تلقائياً للمتابعة."/>}</div></div>
}

export const LostOpportunitiesPage = () => {
  const { companyId, isDemo }=useClinicOS(); const {showToast}=useToast(); const {data:rows=[],loading,refetch}=useClinicOpportunities(companyId,isDemo); const open=rows.filter(r=>r.status!=='closed')
  const follow=async(row:typeof rows[number])=>{window.open(whatsappLink(row.customer_phone,`مرحباً ${row.customer_name||''}، نود مساعدتك في إكمال حجز ${row.interested_service||'الموعد المطلوب'}.`),'_blank');try{await updateClinicOpportunity(row.id,'contacted');await refetch();showToast('تم تسجيل بدء المتابعة','success')}catch{showToast('تعذر تحديث حالة الفرصة','error')}}
  return <div className="clinic-ai-page"><PageHeader title="الفرص الضائعة" subtitle="طلبات لم تتحول إلى حجز بعد، مرتبة لتساعد الفريق على التدخل في الوقت المناسب."/><div className="clinic-kpi-grid"><Metric icon={TrendingUp} label="الفرص المفتوحة" value={open.length} description="تحتاج قراراً" tone="rose"/><Metric icon={Sparkles} label="أولوية عالية" value={open.filter(r=>r.priority==='high').length} description="الأقرب للحجز" tone="amber"/><Metric icon={Clock3} label="بدأت خارج الدوام" value={open.filter(r=>r.opportunity_type?.includes('after_hours')).length} description="حسب مصدر التسجيل" tone="blue"/><Metric icon={PhoneMissed} label="مرتبطة بمكالمة" value={open.filter(r=>r.opportunity_type?.includes('call')).length} description="تحتاج معاودة اتصال"/><Metric icon={CheckCircle2} label="تمت معالجتها" value={rows.filter(r=>r.status==='closed').length} description="من إجمالي الفرص" tone="mint"/></div><div className="clinic-card clinic-section">{loading?<EmptyState icon={Clock3} title="جاري التحميل" body="نرتب الفرص حسب الأولوية."/>:open.length?<div className="clinic-list">{open.map(row=><div className="clinic-list-row" key={row.id}><div><strong>{row.customer_name||'عميل'}</strong><div className="clinic-muted">{row.customer_phone}</div></div><div>{row.opportunity_type||'طلب غير مكتمل'}</div><div>{row.interested_service||'غير محدد'}</div><span className={`clinic-badge ${row.priority==='high'?'danger':'warning'}`}>{row.priority==='high'?'عالية':'متوسطة'}</span><button className="clinic-action secondary" onClick={()=>follow(row)}>{row.suggested_action||'ابدأ المتابعة'}</button></div>)}</div>:<EmptyState icon={TrendingUp} title="لا توجد فرص ضائعة" body="هذا جيد. ستظهر هنا فقط الطلبات التي تحتاج متابعة فعلية."/>}</div></div>
}

export const SmartCallsPage = () => {
  const { packageType,isSubscribed,companyId,isDemo,usageSummary }=useClinicOS(); const {data:calls=[],loading}=useClinicAICalls(companyId,isDemo)
  if(!isSubscribed||packageType!=='ai_pro')return <div className="clinic-ai-page"><UpgradeLocked/></div>
  const booked=calls.filter(c=>c.result==='booked').length, review=calls.filter(c=>c.needs_review).length, seconds=calls.reduce((s,c)=>s+(c.duration_seconds||0),0)
  return <div className="clinic-ai-page"><PageHeader title="المكالمات الذكية" subtitle="كل مكالمة استقبلها الموظف الصوتي ونتيجتها الفعلية."/><div className="clinic-kpi-grid"><Metric icon={Phone} label="المكالمات" value={calls.length} description="ضمن السجل"/><Metric icon={Clock3} label="الدقائق المستخدمة" value={Math.ceil(seconds/60)||usageSummary.smartCallMinutes} description="من دورة الاستخدام" tone="blue"/><Metric icon={CalendarCheck} label="تحولت إلى حجز" value={booked} description="حجوزات مرتبطة" tone="mint"/><Metric icon={TrendingUp} label="تحتاج مراجعة" value={review} description="تدخل بشري مطلوب" tone="amber"/></div><div className="clinic-card clinic-section">{loading?<EmptyState icon={Clock3} title="جاري التحميل" body="نجهز سجل المكالمات."/>:calls.length?<div className="clinic-list">{calls.map(row=><div className="clinic-list-row" key={row.id}><strong>{row.phone}</strong><div>{Math.ceil((row.duration_seconds||0)/60)} د</div><div>{row.intent}</div><div>{row.summary||'لا يوجد ملخص'}</div><span className={`clinic-badge ${row.result==='booked'?'success':row.needs_review?'warning':''}`}>{row.result}</span></div>)}</div>:<EmptyState icon={Phone} title="لا توجد مكالمات بعد" body="ستظهر أول مكالمة هنا بعد تشغيل رقم الموظف الصوتي."/>}</div></div>
}

export const MissedCallsPage = () => {
  const {packageType,isSubscribed,companyId,isDemo}=useClinicOS(); const {data:calls=[],loading}=useClinicAICalls(companyId,isDemo)
  if(!isSubscribed||packageType!=='ai_pro')return <div className="clinic-ai-page"><UpgradeLocked missed/></div>
  const missed=calls.filter(c=>['failed','no_slot','needs_review'].includes(c.result)||c.status==='failed'||c.needs_review), recovered=missed.filter(c=>c.result==='booked'||Boolean(c.appointment_id)).length
  return <div className="clinic-ai-page"><PageHeader title="المكالمات الفائتة" subtitle="المكالمات التي لم تُغلق نتيجتها وتحتاج متابعة واضحة من الفريق."/><div className="clinic-kpi-grid"><Metric icon={PhoneMissed} label="تحتاج متابعة" value={missed.length} description="في السجل الحالي" tone="rose"/><Metric icon={Phone} label="تم إنقاذها" value={recovered} description="ارتبطت بحجز" tone="mint"/><Metric icon={TrendingUp} label="معدل الإنقاذ" value={`${missed.length?Math.round(recovered/missed.length*100):0}%`} description="من الحالات المفتوحة"/></div><div className="clinic-card clinic-section">{loading?<EmptyState icon={Clock3} title="جاري التحميل" body="نراجع نتائج المكالمات."/>:missed.length?<div className="clinic-list">{missed.map(r=><div className="clinic-list-row" key={r.id}><strong>{r.phone}</strong><div>{dateFmt.format(new Date(r.call_time))}</div><span className="clinic-badge warning">{r.review_reason||'تحتاج متابعة'}</span><div>{r.summary||'لا يوجد ملخص'}</div><a className="clinic-action secondary" href={whatsappLink(r.phone,'مرحباً، لاحظنا محاولتك التواصل مع العيادة. كيف يمكننا مساعدتك؟')} target="_blank" rel="noreferrer">متابعة</a></div>)}</div>:<EmptyState icon={PhoneMissed} title="لا توجد مكالمات فائتة" body="لا توجد حالات تحتاج تدخلاً حالياً."/>}</div></div>
}

export const PlanUsagePage = () => {
  const {packageType,isDemo,isSubscribed,usageMetrics,usageCycleStart,usageCycleEnd,subscriptionEndDate,accountLoading}=useClinicOS(); const plan=CLINIC_PLANS[packageType]; const metrics=isDemo?getUsageMetrics(packageType):usageMetrics; const overall=isSubscribed||isDemo?getOverallUsage(packageType,metrics):0
  if(accountLoading)return <LoadingState/>
  return <div className="clinic-ai-page"><PageHeader title="الباقة والاستخدام" subtitle="حدود الخدمات الذكية ودورة الاشتراك من بيانات حسابك الفعلية." action={<a className="clinic-action ghost" href={`${SUPPORT_WHATSAPP}?text=${encodeURIComponent('مرحباً، أحتاج مساعدة بخصوص الباقة والاستخدام.')}`} target="_blank" rel="noreferrer">تواصل مع الإدارة</a>}/><div className="clinic-card clinic-section"><div className="clinic-section-head"><div><h2>{isSubscribed?plan.name:'Free'}</h2><p>{isSubscribed?plan.support:'حساب معاينة بدون خدمات تشغيلية مفعلة.'}</p></div><span className={`clinic-badge ${isSubscribed?'success':''}`}>{isSubscribed?'نشطة':'معاينة'}</span></div><div className="clinic-outcome-grid"><div className="clinic-mini-stat"><span>السعر السنوي</span><strong>{isSubscribed?`${nf.format(plan.annualPrice)} ر.س`:'0 ر.س'}</strong></div><div className="clinic-mini-stat"><span>رسوم التأسيس</span><strong>{isSubscribed?`${nf.format(plan.setupFee)} ر.س`:'—'}</strong></div><div className="clinic-mini-stat"><span>دورة الاستخدام</span><strong className="clinic-small-value">{usageCycleStart&&usageCycleEnd?`${usageCycleStart} - ${usageCycleEnd}`:'تبدأ بعد التفعيل'}</strong></div><div className="clinic-mini-stat"><span>انتهاء الاشتراك</span><strong className="clinic-small-value">{subscriptionEndDate||'غير مفعّل'}</strong></div></div></div><div className="clinic-two-col"><div className="clinic-card clinic-section"><div className="clinic-section-head"><div><h2>استخدام هذا الشهر</h2><p>النسبة العامة تعتمد على أقرب حد للاكتمال.</p></div><strong>{overall}%</strong></div>{metrics.length?metrics.map(m=>{const p=usagePercentage(m);return <div className="clinic-usage-row" key={m.key}><div className="clinic-usage-meta"><span>{m.label}</span><strong>{nf.format(m.used)} / {m.limit?nf.format(m.limit):'غير مفعّل'}</strong></div><div className="clinic-progress"><span style={{width:`${p}%`,background:p>=100?'#d44b5c':p>=80?'#c77a18':'#0f9f78'}}/></div></div>}):<EmptyState title="لا توجد حدود استخدام" body="تظهر الحدود فور تثبيت الاشتراك."/>}</div><div className="clinic-card clinic-section"><div className="clinic-section-head"><h2>{packageType==='whatsapp'?'فعّل الاتصال الذكي':'أنت على أعلى باقة'}</h2></div><p className="clinic-muted">{packageType==='whatsapp'?'أضف الرد الصوتي خارج الدوام وتحويل المكالمات إلى حجوزات.':'الباقة الحالية تشمل واتساب والاتصال الذكي واستعادة المكالمات.'}</p>{packageType==='whatsapp'&&<Link className="clinic-action" to="/clinic-os/dashboard/plans">عرض الباقات</Link>}</div></div></div>
}

const knowledgeTabs=[['clinic','معلومات العيادة'],['doctors','الأطباء'],['services','الخدمات والأسعار'],['hours','أوقات العمل'],['branches','الفروع'],['faq','الأسئلة الشائعة'],['policy','سياسة الحجز والإلغاء'],['payments','طرق الدفع'],['offers','العروض']] as const
export const KnowledgeCenterPage=()=>{
  const {companyId,isDemo,clinicName}=useClinicOS(); const {showToast}=useToast(); const [tab,setTab]=useState<string>(knowledgeTabs[0][0]); const [draft,setDraft]=useState(''); const [saving,setSaving]=useState(false)
  const {data:items=[],loading,refetch}=useClinicKnowledge(companyId,isDemo); const {data:doctors=[]}=useClinicDoctors(companyId,isDemo); const {data:services=[]}=useClinicServices(companyId,isDemo)
  const item=items.find(i=>i.type===tab); const generated=tab==='clinic'?`اسم العيادة: ${clinicName||'غير محدد'}`:tab==='doctors'?doctors.map(d=>`${d.name} — ${d.specialty}`).join('\n'):tab==='services'?services.map(s=>`${s.name} — ${nf.format(Number(s.price||0))} ر.س — ${s.duration_minutes} دقيقة`).join('\n'):''; const value=draft||(item?.content??generated)
  const changeTab=(next:string)=>{setTab(next);setDraft('')}; const save=async()=>{if(!companyId)return;setSaving(true);try{await saveClinicKnowledgeItem({id:item?.id,company_id:companyId,type:tab,title:knowledgeTabs.find(t=>t[0]===tab)?.[1]||tab,content:value});await refetch();setDraft('');showToast('تم حفظ معلومات موظف الاستقبال الذكي','success')}catch{showToast('تعذر حفظ المعلومات','error')}finally{setSaving(false)}}
  return <div className="clinic-ai-page"><PageHeader title="مركز المعرفة" subtitle="المصدر الذي يعتمد عليه موظف الاستقبال الذكي للإجابة بدقة وعدم اختراع معلومات."/><div className="clinic-card"><div className="clinic-tabbar">{knowledgeTabs.map(([key,label])=><button key={key} onClick={()=>changeTab(key)} className={`clinic-tab ${tab===key?'active':''}`}>{label}</button>)}</div><div className="clinic-section"><div className="clinic-section-head"><div><h2>{knowledgeTabs.find(t=>t[0]===tab)?.[1]}</h2><p>اكتب معلومات واضحة ومحدّثة كما تريد أن يشرحها الموظف الذكي للمرضى.</p></div><button className="clinic-action" onClick={save} disabled={saving}>{saving?'جاري الحفظ...':'حفظ التغييرات'}</button></div>{loading?<EmptyState icon={Clock3} title="جاري التحميل" body="نحمّل قاعدة معرفة العيادة."/>:<div className="clinic-field"><label>المحتوى المعتمد</label><textarea className="clinic-knowledge-editor" value={value} onChange={e=>setDraft(e.target.value)} placeholder="أضف المعلومات هنا..."/><small>لن يجيب الموظف الذكي بمعلومات غير موجودة هنا أو في بيانات الأطباء والخدمات.</small></div>}</div></div></div>
}

export const BookingsPage=()=>{
  const navigate=useNavigate(); const {companyId,isDemo}=useClinicOS(); const [filter,setFilter]=useState('اليوم'); const {data:appointments=[],loading}=useClinicAppointments(companyId,undefined,isDemo); const today=new Date().toISOString().slice(0,10)
  const rows=appointments.filter(a=>{if(filter==='اليوم')return a.appointment_date===today;if(filter==='هذا الأسبوع'){const delta=(new Date(a.appointment_date).getTime()-new Date(today).getTime())/86400000;return delta>=0&&delta<7}if(filter==='هذا الشهر')return a.appointment_date.startsWith(today.slice(0,7));const map:Record<string,string>={'مؤكد':'confirmed','بانتظار التأكيد':'pending','يحتاج مراجعة':'needs_review','ملغي':'cancelled'};return a.status===map[filter]})
  return <div className="clinic-ai-page"><PageHeader title="الحجوزات" subtitle="كل الحجوزات المسجلة فعلياً مع مصدر الحجز وحالته." action={<button className="clinic-action" onClick={()=>navigate('/clinic-os/dashboard/appointments')}>إضافة موعد</button>}/><div className="clinic-filter-row">{['اليوم','هذا الأسبوع','هذا الشهر','مؤكد','بانتظار التأكيد','يحتاج مراجعة','ملغي'].map(f=><button onClick={()=>setFilter(f)} className={`clinic-filter ${filter===f?'active':''}`} key={f}>{f}</button>)}</div><div className="clinic-card clinic-section">{loading?<EmptyState icon={Clock3} title="جاري التحميل" body="نحمّل الحجوزات."/>:rows.length?<div className="clinic-list">{rows.map(r=><button className="clinic-list-row clinic-row-button" key={r.id} onClick={()=>navigate('/clinic-os/dashboard/appointments')}><div><strong>{r.patient_name||'مريض'}</strong><div className="clinic-muted">{r.patient_phone}</div></div><div>{r.service_name||'خدمة غير محددة'}</div><div>{r.appointment_date} · {r.start_time?.slice(0,5)}</div><span className={`clinic-badge ${r.status==='confirmed'?'success':r.status==='cancelled'?'danger':'warning'}`}>{r.status}</span><span className="clinic-action secondary">عرض وإدارة</span></button>)}</div>:<EmptyState icon={CalendarCheck} title="لا توجد حجوزات ضمن هذا الفلتر" body="أضف أول موعد أو اختر فترة أخرى." action={<button className="clinic-action" onClick={()=>navigate('/clinic-os/dashboard/appointments')}>إضافة موعد</button>}/>}</div></div>
}
