import { BarChart3, CalendarCheck, Clock3, Download, MessageCircle, Phone, TrendingUp } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import './clinic-ai-dashboard.css'

const weekly=[{day:'الأحد',bookings:5,conversations:18},{day:'الاثنين',bookings:7,conversations:24},{day:'الثلاثاء',bookings:4,conversations:17},{day:'الأربعاء',bookings:8,conversations:29},{day:'الخميس',bookings:9,conversations:31},{day:'الجمعة',bookings:3,conversations:11},{day:'السبت',bookings:6,conversations:18}]
const services=[{name:'تنظيف الأسنان',requests:16,bookings:11},{name:'كشف عام',requests:13,bookings:9},{name:'تقويم شفاف',requests:10,bookings:7},{name:'زراعة أسنان',requests:8,bookings:5}]

export const Reports=()=> <div className="clinic-ai-page">
  <div className="clinic-ai-header"><div><h1>تقارير أداء موظف الاستقبال الذكي</h1><p>اعرف كيف تحولت المحادثات والمكالمات إلى حجوزات، وأين توجد فرص تحتاج قراراً.</p></div><button className="clinic-action"><Download size={14}/>تصدير التقرير</button></div>
  <div className="clinic-kpi-grid"><K icon={CalendarCheck} label="حجوزات أنجزها النظام" value="42" note="هذا الشهر"/><K icon={MessageCircle} label="محادثات تم التعامل معها" value="148" note="واتساب"/><K icon={Clock3} label="عملاء خارج الدوام" value="27" note="تم الرد عليهم"/><K icon={Phone} label="مكالمات تم إنقاذها" value="11" note="عادت لمسار الحجز"/><K icon={TrendingUp} label="معدل التحويل" value="28%" note="محادثة إلى حجز"/></div>
  <div className="clinic-two-col"><div className="clinic-card clinic-section"><div className="clinic-section-head"><h2>الحجوزات والمحادثات حسب اليوم</h2></div><ResponsiveContainer width="100%" height={280}><LineChart data={weekly}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip/><Line dataKey="conversations" name="المحادثات" stroke="#6557d9" strokeWidth={3}/><Line dataKey="bookings" name="الحجوزات" stroke="#0f9f78" strokeWidth={3}/></LineChart></ResponsiveContainer></div><div className="clinic-card clinic-section"><div className="clinic-section-head"><h2>مصادر النتائج</h2></div><ResponsiveContainer width="100%" height={280}><BarChart data={[{name:'واتساب',value:26},{name:'اتصال ذكي',value:10},{name:'يدوي',value:6}]}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip/><Bar dataKey="value" fill="#6557d9" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div>
  <div className="clinic-card clinic-section"><div className="clinic-section-head"><div><h2>الخدمات الأكثر طلباً</h2><p>الطلب مقابل الحجوزات التي اكتملت.</p></div></div><div className="clinic-list">{services.map((s,i)=><div className="clinic-list-row" key={s.name} style={{gridTemplateColumns:'1.4fr .8fr .8fr 2fr'}}><strong>{i+1}. {s.name}</strong><span>{s.requests} طلباً</span><span className="clinic-badge success">{s.bookings} حجوزات</span><div className="clinic-progress"><span style={{width:`${Math.round(s.bookings/s.requests*100)}%`}}/></div></div>)}</div></div>
</div>

const K=({icon:Icon,label,value,note}:{icon:typeof BarChart3;label:string;value:string;note:string})=><div className="clinic-card clinic-kpi"><div className="clinic-kpi-icon" style={{background:'#f0efff',color:'#6557d9'}}><Icon size={18}/></div><div className="clinic-kpi-label">{label}</div><div className="clinic-kpi-value">{value}</div><div className="clinic-kpi-description">{note}</div></div>
