import { BarChart3, CalendarCheck, Clock3, Download, MessageCircle, Phone, TrendingUp } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useClinicOS } from '../../../context/ClinicOSContext'
import { useClinicAICalls, useClinicAppointments, useClinicMessages, useClinicOpportunities, useClinicServices } from '../../../lib/clinicOSQueries'
import { useToast } from '../../../components/clinicOS/ui/Toast'
import './clinic-ai-dashboard.css'

const nf = new Intl.NumberFormat('ar-SA')
const days = ['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت']

export const Reports=()=>{
  const {companyId,isDemo,usageSummary}=useClinicOS(); const {showToast}=useToast()
  const {data:appointments=[],loading}=useClinicAppointments(companyId,undefined,isDemo); const {data:messages=[]}=useClinicMessages(companyId,isDemo); const {data:calls=[]}=useClinicAICalls(companyId,isDemo); const {data:opportunities=[]}=useClinicOpportunities(companyId,isDemo); const {data:services=[]}=useClinicServices(companyId,isDemo)
  const month=new Date().toISOString().slice(0,7); const monthAppointments=appointments.filter(a=>a.appointment_date.startsWith(month)); const bookings=monthAppointments.filter(a=>!['cancelled','no_show'].includes(a.status)).length; const completed=monthAppointments.filter(a=>a.status==='completed').length; const conversations=usageSummary.conversations||new Set(messages.map(m=>m.recipient_phone)).size; const conversion=conversations?Math.round(bookings/conversations*100):0
  const weekly=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const key=d.toISOString().slice(0,10);return{day:days[d.getDay()],bookings:appointments.filter(a=>a.appointment_date===key).length,messages:messages.filter(m=>m.created_at?.slice(0,10)===key).length}})
  const sourceData=Object.entries(monthAppointments.reduce<Record<string,number>>((a,r)=>{a[r.source||'manual']=(a[r.source||'manual']||0)+1;return a},{})).map(([name,value])=>({name:({ai_booking:'حجز ذكي',whatsapp:'واتساب',reception:'الاستقبال',website:'الموقع',manual:'يدوي'} as Record<string,string>)[name]||name,value}))
  const serviceRows=Object.entries(monthAppointments.reduce<Record<string,{requests:number;completed:number}>>((a,r)=>{const key=r.service_name||'غير محدد';a[key]??={requests:0,completed:0};a[key].requests++;if(r.status==='completed')a[key].completed++;return a},{})).map(([name,v])=>({name,...v})).sort((a,b)=>b.requests-a.requests)
  const exportCsv=()=>{const rows=[['المريض','الجوال','الخدمة','التاريخ','الوقت','المصدر','الحالة'],...monthAppointments.map(a=>[a.patient_name,a.patient_phone,a.service_name,a.appointment_date,a.start_time,a.source,a.status])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`clinic-report-${month}.csv`;link.click();URL.revokeObjectURL(url);showToast('تم تصدير التقرير','success')}
  return <div className="clinic-ai-page"><div className="clinic-ai-header"><div><h1>تقارير أداء موظف الاستقبال الذكي</h1><p>أرقام فعلية من محادثات وحجوزات ومكالمات حساب العيادة، بدون تقديرات وهمية.</p></div><button className="clinic-action" onClick={exportCsv} disabled={loading}><Download size={14}/>تصدير CSV</button></div><div className="clinic-kpi-grid"><K icon={CalendarCheck} label="الحجوزات" value={nf.format(bookings)} note="هذا الشهر"/><K icon={MessageCircle} label="المحادثات" value={nf.format(conversations)} note="عملاء فريدون"/><K icon={Clock3} label="خارج الدوام" value={nf.format(usageSummary.afterHours)} note="تم التعامل معهم"/><K icon={Phone} label="المكالمات" value={nf.format(calls.length)} note="في السجل"/><K icon={TrendingUp} label="معدل التحويل" value={`${conversion}%`} note="محادثة إلى حجز"/><K icon={BarChart3} label="مواعيد مكتملة" value={nf.format(completed)} note="هذا الشهر"/></div>{!appointments.length&&!messages.length&&!calls.length?<div className="clinic-card clinic-empty-state"><BarChart3 size={25}/><strong>التقرير جاهز وينتظر أول عملية</strong><span>ستظهر الرسوم تلقائياً بعد أول حجز أو رسالة أو مكالمة.</span></div>:<><div className="clinic-two-col"><div className="clinic-card clinic-section"><div className="clinic-section-head"><h2>الحجوزات والرسائل خلال 7 أيام</h2></div><ResponsiveContainer width="100%" height={280}><LineChart data={weekly}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis allowDecimals={false}/><Tooltip/><Line dataKey="messages" name="الرسائل" stroke="#6557d9" strokeWidth={3}/><Line dataKey="bookings" name="الحجوزات" stroke="#0f9f78" strokeWidth={3}/></LineChart></ResponsiveContainer></div><div className="clinic-card clinic-section"><div className="clinic-section-head"><h2>مصادر الحجوزات</h2></div>{sourceData.length?<ResponsiveContainer width="100%" height={280}><BarChart data={sourceData}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" name="الحجوزات" fill="#6557d9" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer>:<div className="clinic-empty-state"><span>لا توجد مصادر حجز في الفترة الحالية.</span></div>}</div></div><div className="clinic-card clinic-section"><div className="clinic-section-head"><div><h2>الخدمات الأكثر طلباً</h2><p>الحجوزات مقابل المواعيد المكتملة خلال الشهر.</p></div></div>{serviceRows.length?<div className="clinic-list">{serviceRows.map((s,i)=><div className="clinic-list-row" key={s.name} style={{gridTemplateColumns:'1.4fr .8fr .8fr 2fr'}}><strong>{i+1}. {s.name}</strong><span>{s.requests} حجز</span><span className="clinic-badge success">{s.completed} مكتمل</span><div className="clinic-progress"><span style={{width:`${s.requests?Math.round(s.completed/s.requests*100):0}%`}}/></div></div>)}</div>:<div className="clinic-empty-state"><span>لا توجد خدمات محجوزة بعد.</span></div>}</div></>}</div>
}

const K=({icon:Icon,label,value,note}:{icon:typeof BarChart3;label:string;value:string;note:string})=><div className="clinic-card clinic-kpi"><div className="clinic-kpi-icon" style={{background:'#f0efff',color:'#6557d9'}}><Icon size={18}/></div><div className="clinic-kpi-label">{label}</div><div className="clinic-kpi-value">{value}</div><div className="clinic-kpi-description">{note}</div></div>
