import { useState } from 'react'
import { Bell, Building2, LockKeyhole, MessageCircle, Save, ShieldCheck, UserRoundCog } from 'lucide-react'
import { useClinicOS } from '../../../context/ClinicOSContext'
import { CLINIC_PLANS } from '../../../lib/clinicOSProduct'
import './clinic-ai-dashboard.css'

const sections=[['العيادة',Building2],['الحساب',UserRoundCog],['الإشعارات',Bell],['واتساب',MessageCircle],['الأمان والخصوصية',ShieldCheck]] as const

export const Settings=()=>{
 const {clinicName,userName,packageType}=useClinicOS(); const [section,setSection]=useState('العيادة')
 return <div className="clinic-ai-page"><div className="clinic-ai-header"><div><h1>الإعدادات</h1><p>إعدادات واضحة للعيادة والحساب والرسائل، بدون تفاصيل تقنية معقدة.</p></div><button className="clinic-action"><Save size={14}/>حفظ التغييرات</button></div><div className="clinic-two-col" style={{gridTemplateColumns:'230px minmax(0,1fr)'}}><div className="clinic-card clinic-section" style={{padding:9,height:'max-content'}}>{sections.map(([label,Icon])=><button key={label} onClick={()=>setSection(label)} style={{width:'100%',display:'flex',alignItems:'center',gap:9,padding:'10px',borderRadius:7,border:0,background:section===label?'#f0efff':'transparent',color:section===label?'#5146bd':'#5f6b7d',font:'800 11px Cairo',cursor:'pointer'}}><Icon size={15}/>{label}</button>)}<button onClick={()=>setSection('الباقة والاستخدام')} style={{width:'100%',display:'flex',alignItems:'center',gap:9,padding:'10px',borderRadius:7,border:0,background:section==='الباقة والاستخدام'?'#f0efff':'transparent',color:section==='الباقة والاستخدام'?'#5146bd':'#5f6b7d',font:'800 11px Cairo',cursor:'pointer'}}><LockKeyhole size={15}/>الباقة والاستخدام</button></div><div className="clinic-card clinic-section"><SectionContent section={section} clinicName={clinicName} userName={userName} packageType={packageType}/></div></div></div>
}

const SectionContent=({section,clinicName,userName,packageType}:{section:string;clinicName:string;userName:string;packageType:'whatsapp'|'ai_pro'})=>{
 if(section==='الباقة والاستخدام')return <><div className="clinic-section-head"><div><h2>الباقة والاستخدام</h2><p>حالة اشتراك العيادة الحالية.</p></div><span className="clinic-badge success">نشطة</span></div><div className="clinic-outcome-grid"><S label="الباقة الحالية" value={CLINIC_PLANS[packageType].name}/><S label="بداية الاشتراك" value="12 يونيو 2026"/><S label="نهاية الاشتراك" value="12 يونيو 2027"/><S label="الدعم" value={CLINIC_PLANS[packageType].support}/></div></>
 if(section==='الإشعارات')return <><H title="الإشعارات" sub="اختر التنبيهات التي تصل لفريق العيادة."/>{['تنبيهات الحجوزات','تنبيهات الفرص الضائعة','تنبيه الوصول إلى 80%','تنبيه الوصول إلى 100%','تنبيه انتهاء الاشتراك'].map(x=><Toggle key={x} label={x}/>)}</>
 if(section==='واتساب')return <><H title="إعدادات واتساب" sub="النصوص الأساسية المستخدمة أثناء استقبال العملاء."/><div className="clinic-form-grid"><F label="رقم واتساب العيادة" value="+966 54 666 6005"/><F label="رسالة الترحيب" value="مرحباً بك، كيف يمكننا مساعدتك؟"/><F label="رسالة خارج الدوام" value="نحن خارج وقت الدوام، وسنساعدك في اختيار الموعد المناسب."/><F label="رسالة التحويل للموظف" value="تم تحويل طلبك إلى فريق العيادة للمتابعة."/></div></>
 if(section==='الحساب')return <><H title="إعدادات الحساب" sub="بيانات المستخدم الذي يدير لوحة العيادة."/><div className="clinic-form-grid"><F label="اسم المستخدم" value={userName||'مدير العيادة'}/><F label="البريد الإلكتروني" value="clinic-dev@madar.software"/><F label="الدور" value="مالك"/><F label="اللغة" value="العربية"/></div></>
 if(section==='الأمان والخصوصية')return <><H title="الأمان والخصوصية" sub="حافظ على وصول آمن إلى بيانات العيادة."/><div className="clinic-form-grid"><button className="clinic-action ghost">تغيير كلمة المرور</button><button className="clinic-action ghost">عرض سجل الدخول</button><button className="clinic-action ghost">تسجيل الخروج من كل الأجهزة</button><button className="clinic-action ghost">سياسة الخصوصية</button></div></>
 return <><H title="إعدادات العيادة" sub="تظهر هذه المعلومات في الحساب ورسائل الاستقبال."/><div className="clinic-form-grid"><F label="اسم العيادة" value={clinicName||'عيادة نور للأسنان'}/><F label="رقم التواصل" value="+966 54 666 6005"/><F label="البريد الإلكتروني" value="info@noorclinic.sa"/><F label="المدينة" value="الرياض"/><F label="الموقع" value="حي الياسمين"/><F label="رابط خرائط جوجل" value="https://maps.google.com"/></div></>
}
const H=({title,sub}:{title:string;sub:string})=><div className="clinic-section-head"><div><h2>{title}</h2><p>{sub}</p></div></div>
const F=({label,value}:{label:string;value:string})=><div className="clinic-field"><label>{label}</label><input defaultValue={value}/></div>
const S=({label,value}:{label:string;value:string})=><div className="clinic-mini-stat"><span>{label}</span><strong style={{fontSize:14,lineHeight:1.6}}>{value}</strong></div>
const Toggle=({label}:{label:string})=><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'13px 0',borderBottom:'1px solid #eef1f6'}}><span style={{font:'700 12px Cairo'}}>{label}</span><input type="checkbox" defaultChecked aria-label={label}/></div>
